@Entry
@Component
struct Index {

  build() {
    RelativeContainer() {
      Text('A_Feature')
        .id('A_Feature')
        .fontSize(50)
        .fontWeight(FontWeight.Bold)
        .alignRules({
          center: { anchor: '__container__', align: VerticalAlign.Center },
          middle: { anchor: '__container__', align: HorizontalAlign.Center }
        })
    }
    .height('100%')
    .width('100%')
  }
}